[package]
name = "keepass"
version = "0.0.1"
authors = ["Matt Thomson <mattjohnthomson@gmail.com>"]

[dependencies]

byteorder = "0.4"
flate2 = "0.2"
rust-crypto = "0.2"
rustc-serialize = "0.3"
xml-rs = "0.3"
